id: I3EED2DBC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T03:56:27+00:00'
last_modified: '2022-06-08T12:58:01.463040+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74520
  title: ཕར་ཕྱིན་གྱི་མཐའ་དཔྱོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0B5B:
      image_group_id: I4CZ74522
      title: Volume 1 of phar phyin gyi mtha' dpyod/
      total_pages: 728
      order: 1
      base_file: 0B5B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
