id: P006958
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74520
  title: ཕར་ཕྱིན་གྱི་མཐའ་དཔྱོད།
  author: ''
  volumes:
    fcf7fd23526948da92b018cdf6086a7f:
      image_group_id: I4CZ74522
      title: ''
      volume_number: 1
      total_pages: 728
ebook_metadata:
  title: ཕར་ཕྱིན་གྱི་མཐའ་དཔྱོད།
  author: ''
  sku: P006958
  cover: cover.jpg
  layers:
  - pagination
