id: P006958
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W4CZ74520
  title: ཕར་ཕྱིན་གྱི་མཐའ་དཔྱོད།
  author: ''
  volumes:
    997b27ede4134b96bbb9ab1dae21c192:
      image_group_id: I4CZ74522
      title: Volume 1 of phar phyin gyi mtha' dpyod/
      volume_number: 1
      total_pages: 728
      base_file: v001.txt
